###
POST http://127.0.0.1:5000/signup
Content-Type: application/json

{
    "username": "ronytan1",
    "password": "12345678"
}

####
POST http://127.0.0.1:5000/signin
Content-Type: application/json

{
    "username": "ronytan1",
    "password": "12345678"
}

################################################
GET http://localhost:5000/getjadwal/1



################################################

GET http://localhost:5000/getlokasibus

####
GET http://localhost:5000/getnonaktifbus

###
GET http://localhost:5000/getlokasibus/2


########################################HALTE################################################

###
GET http://localhost:5000/getlokasihalte

###
GET http://localhost:5000/getlokasihalte/23

###
POST  http://localhost:5000/getnearesthalte
Content-Type: application/json

{
    "latitude": -7.832355,
    "longitude":   111.984223
}

###
POST  http://localhost:5000/getjadwal/1
Content-Type: application/json

{
    "jadwal_datang": "17:00"
}

##############################PRIVATE############################
###
PATCH  http://localhost:5000/updatebus
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzMyMTc1ODc3fQ.PHaR6cqVSBGCbDNjG_FNlmnUfPdDGoNgkHn4QjGCBbc


{
    "id": 6,
    "lat": -7.827515,
    "long": 111.999004
}


###
PATCH  http://localhost:5000/setaktifbus/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDU2NzY3NjZ9.p7hBYp71spejIohWGFuDPtuBlpMByOr8ctfuCFNsPIk

{
    "id": 6,
    "id_pengemudi" : 2
}

###
PATCH  http://localhost:5000/setnonaktifbus/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDU2NzY3NjZ9.p7hBYp71spejIohWGFuDPtuBlpMByOr8ctfuCFNsPIk

{
  "id": 6,
  "id_pengemudi" : 2
}